### ISSUE TITLE
Rename **check-unsed-selectors** to **check-unused-flux-dependencies**

### ISSUE THREAD

**Issue by jukben** [productboardlabs/tslint-pb#14]
I think it makes more sense. What do you think @mauricekleine? To keep it consistent.

**Comment by mauricekleine** [comment]
@jukben not sure about this one; I think selectors as a concept is always used in a flux context, so just using 'selectors' instead of 'flux-selectors' might be self-explanatory. Unless there's use cases in which 'selectors' isn't used in a flux context.

The reason I suggested to rename 'sort-dependencies' to 'sort-flux-dependencies' was that the former could also relate to non-flux stuff in my view.

**Comment by jukben** [comment]
Yep, the issue is that the rule also applies to stores – which is flux dependency as well as a selector, but it not very obvious from the rule name. What do you think?

**Comment by mauricekleine** [comment]
@jukben in that case, YES! Rename that sweet sweet rule 🎉

**Comment by jukben** [comment]
closed in #dbd20b9ae2cc4ba8bf5cae68cbd339554d799b1d
